### ISSUE TITLE
Preset Editor not saving some fields in Equipment Slots

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#42]
- It's not saving the preset selected on the dropdown menu when using the option "Use preset" in "Actor filters" and "Item Filters" for an equipment.
- It's not saving whatever is defined in "Item filter conditions" for an equipment.

Speaking of filters, is there any way to add a sort of blacklist for items in "Gear nodes", so that the items can be ignored in gear nodes and consequently in "Equipment slots"? I'm trying to filter out some items, it works at some extent using the functions from the "Display manager" but when the item is equipped, it gets managed via gear nodes.

**Comment by SlavicPotato** [comment]
What do you mean by "filter out"? Display filters block certain items from being displayed. Nothing in this mod can prevent the game from equipping items, the most you can do via gear nodes is hide a parent node where some equipped item geometry may be.

For example, the game equips a sword and attaches its geometry to ```WeaponDagger```, the node tree structure looks like:

![sshot](https://user-images.githubusercontent.com/66538381/233256923-74d1e35d-da40-4e94-b1d7-478e3ce52d87.png)

You can hide conditionally ```CME WeaponDaggerAnkle``` via the visibility options in gear nodes, so anything attached to it will be hidden as well, but that won't at all affect the game's equipment system. To put it another way, IED doesn't manage equipped items, just what may or may not be their parent nodes.

**Comment by GiraPomba** [comment]
I was trying to change a weapon from the 'Sword" node to the "Sword back" node, while still having the other swords using the default position. I created an override in Gear node>placement. 
IED changed the position of the weapon when equipped as expected, but then set the other sword to the "Sword left" position, as if you are dual wielding. I created a workaround for that, by changing the "Sword left" node to use the "Sword" node and added some filters..

Then I remember that IED doesn't do that for Bound Weapons, so there must be a sort of blacklist or something.. I could create the displays using custom view..

**Comment by SlavicPotato** [comment]
Oh ok, this is about bound weapons. They're not included in the equipment selection process but they are recognized as equipped weapons, that's why the corresponding display slot disables once it's equipped. I guess that could be changed, I don't think there would be any side effects except it might look a bit weird while sheathing the bound weap. This change wouldn't affect conditions though.

**Comment by GiraPomba** [comment]
Yeah, but if you have a one handed sword favorited and then equip a bound sword, the favorited sword is not sent to the left node, right? So I guess the bound weapons are not considered in this case. I wonder if the same functionality could be used for other weapons.

**Comment by SlavicPotato** [comment]
> Yeah, but if you have a one handed sword favorited and then equip a bound sword, the favorited sword is not sent to the left node, right?

Oh, I just checked and it seems that change was already implemented at some point, so nvm the last post, I completely forgot that was done.

I'm still confused about what you're talking about since you're conflating gear positioning and equipment selection, these two systems have nothing to do with each other. Maybe you didn't disambiguate between left and right hand when setting up gear pos override conditions? Ie you used 'form' condition instead of 'type'? 

Anyway, closing this since the original issue was solved.

**Comment by GiraPomba** [comment]
Maybe I didn't express myself properly earlier.

So, I'm trying to separate a specific weapon that uses the one handed sword node from the others one handed swords. I changed the node for that sword to the sword back.

If I have this specific sword equipped and the other one handed swords favorited, they're placed in the one handed left sword node, because IED disables the Equipment slot for that weapon an enables the left node when possible...

I gave the example of the bound swords, because they are "ignored" in this scenario. 

The question is: can the same functionality be applied to specific weapons? Maybe a system with conditions and such..

**Comment by SlavicPotato** [comment]
I don't think you've though this through. A slot can't be occupied by any display while it's in-game counterpart is equipped, it might have geometry attached to the body (the sheath), what happens to that? Do we attempt to move it, hide it? Bound weapons are filtered out this way because they don't have scabbards and aren't sheathable.

**Comment by GiraPomba** [comment]
Oh, ok. I was thinking to just filter out like the bound weapons, but with a condition (Type>Sword>Keyword), but if it's not possible, nevermind then.

**Comment by SlavicPotato** [comment]
It's possible but it's nonsense lol. I'd essentially allow a user to break the equipment system. Bound weapons are a special case that needs special handling in several spots (what you refer to as 'filtered out') or things get weird, do the same for any regular piece of gear and things would break or make a nonsensical display, like a weapon overlapping with an equipped scabbard. 

> I created a workaround for that, by changing the "Sword left" node to use the "Sword" node and added some filters...

Conditionally moving nodes around is way to go about it, so you were on the right track here...

**Comment by GiraPomba** [comment]
Yeah, that makes sense.
I'll use what I have at the moment. It works fine, unless you want to display dual swords together, then it needs some tweaking haha.
