### ISSUE TITLE
Daggers at Back Hip and Scabbards

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#45]
The Dagger at Back Hip position/node uses inverted models for the daggers and so does the scabbards.
So, when you use the daggers on this position, the right scabbard is sticking out and the left scabbard is at the correct position.

But if the synthesis patcher has been ran, IED inverts the left scabbard, making both stick out.

Could IED apply the left scabbard fix differently on this node? Apply the left scabbard for the right dagger and don't for the left?

Also, how can I adjust a left scabbard for a weapon? I have a scabbard that it's a bit way off from the weapon.

**Comment by SlavicPotato** [comment]
>The Dagger at Back Hip position/node uses inverted models for the daggers and so does the scabbards.

The right side nodes are positioned so that any dagger attached to it is turned the "wrong" way.

> Could IED apply the left scabbard fix differently on this node? Apply the left scabbard for the right dagger and don't for the left?

A scabbard is chosen after the mesh is loaded and its counterpart is removed, flipping between the two on-demand would require keeping both in memory (or worse, reloading the whole model) which would be wasteful.

The way to solve this is by editing the skeleton mesh (fix the pos/rotation on CME->MOV->DaggerHip, idk the exact names for those just look them up in skeleton explorer), same goes for any scabbard that wasn't generated properly.

**Comment by GiraPomba** [comment]
Okay, thanks.
