### ISSUE TITLE
Type condition with Last equipped

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#46]
There is a difference in the behavior of the Type condition between the lastest version available here and 1.6.3 on Nexus.
It could be a potential bug or an old bug that was solved. I tried reading the commits but couldn't find something.

In custom view, with version 1.6.3, the display below is showing the last two-handed sword equipped with "Equipped" and "This" arguments toggled in the Type condition: [Picture](https://i.imgur.com/ae8N7hI.png).
With RC 18, however, the sword is not being displayed. 
Untoggling "Equipped" makes the sword appear and so does toggling "Or displayed".

**Comment by SlavicPotato** [comment]
That expression reads as: IF a two-handed weapon is equipped (right hand) AND the filtered item is a two-handed weapon THEN return true. So, the item will be accepted only if there's already an item of the same type equipped.

If that aligns with the actual state of things (i.e. you didn't have a 2h weap equipped while testing) then that's correct behavior and 1.6 was incorrect.

That expression makes little sense for any practical use though.

**Comment by GiraPomba** [comment]
Hmm, I see. 
I was interpreting this differently. I thought that last equipped item would search for a "history" of equipped items that fit the conditions. The condition above would be like: Last Two Handed Sword that was equipped.

But toggling Or Displayed also enabled the displayed, even if it wasn't being displayed somewhere else, like a favorited item in equipment slots. Also, nothing was equipped at the moment.

With only "This" it worked too, but I also thought that in order for "This" to work, you would also need to toggle "Equipped" or "Or Displayed". Well, anyway, I'll change the conditions with something different, like combining with "Presence" maybe...

**Comment by SlavicPotato** [comment]
>I was interpreting this differently. I thought that last equipped item would search for a "history" of equipped items that fit the conditions. The condition above would be like: Last Two Handed Sword that was equipped.

Conditions are generic, their basic operation doesn't change depending on where they're used from, though there are differences in what data is available depending on where a condition is used - `Equipped`, `All`/`This` are targetting parameters: 

* `Equipped` runs on items equipped by the game and should always be available (there was probably a mistake in 1.6 that disabled it in last-equipped mode and it got silently fixed at some point)
* `All` runs on all equipment display items (but not custom) and is available everywhere except under equipment display conditions (equipment displays have not yet finished processing by that point so it wouldn't make sense to use it there)
* `This` runs on a specific item that's passed to the condition evaluation funcs, which only happens in filters or on displays. It's not available on conditional variable overrides for example, since there's nothing to target there.

During last-equipped item selection we loop through each known item that was found to be equipped at some point (sorted by last-seen time, descending), running filter conditions on each one and passing along the item so it _may_ be targetted by checking `This`. The first item to pass (conditions evaulate to true) is selected (not necessarily displayed since there are other parameters that need to be satisfied).

Assuming that `Equipped` somehow means something else in filters was misguided, I get that you're looking at it intuitively but that's not how things work. Granted that there's a serious lack of documentation but this much atleast is explained in the tooltip.

**Comment by GiraPomba** [comment]
Thanks for clarifying. Yeah, I've read the tooltip and I know there isn't much documentation about the functions, so I was assuming how it works with playtesting basically, hence the confusion between versions. Looking at it now, makes complete sense, but a bit complex still... 

I will update my presets and tutorials when the new version hits Nexus. I think just toggling "This" will suffice for what I'm trying to do...

Btw, is the "Shield (hand)" node only managed when SDS is disabled? I wonder if it could be used as an override in "Placement". So you can move the shield back and forth with overrides, currently I'm using custom displays with last equipped, it gets the job done, but still...

**Comment by SlavicPotato** [comment]
You want to control whether the shield is equipped/displayed in the hand, or?

That's doable with [Skeleton Extensions](https://github.com/SlavicPotato/ied-dev/files/11443274/ShieldTest.zip) (goes to SkeletonExtensions\ExtraGearNodes folder), but you'll need to adjust xfrm_mov/xfrm_node to fit nicely in the hand and you'll want an invisibility condition for when the hands are drawn since the display always shows (you can also just set the display to disable in this case in equipment manager)

**Comment by GiraPomba** [comment]
I was thinking about the "Placement" view of "Gear nodes"
There is a Shield option there, but no other nodes available (Unrestricted placement doesn't show Shield hand). Maybe it's more complex than that, since it's SDS that moves the shield to the back.

About skeleton extensions, I will give it a try and see what I can do. Haven't tested this yet, but it seems like you can create new nodes?

**Comment by GiraPomba** [comment]
I tried the skeleton extender thing but it looks like it's not reading the "rot" from the json. 
The "pos" and "scale" are applied normally. Is there anything else to change?

**Comment by SlavicPotato** [comment]
Doubt that, more likely you're doing something weird. Rotation is in radians btw.

**Comment by GiraPomba** [comment]
Could be lol, I tried the file you provided, changed the position, rotation and scale. 
It only loaded the position and scale. Checking in skeleton explorer, the rotation values stayed at zero.

**Comment by SlavicPotato** [comment]
Both the mov and the leaf node have configurable transforms (`MOV IEDShieldHand` and `IEDShieldHand` in the example with `xfrm_mov` and `xfrm_node` in the config, respectively). Look at Default.json for reference.

**Comment by GiraPomba** [comment]
Yeah, I changing those values in the json, but it doesn't take effect for the rotation in game.

**Comment by SlavicPotato** [comment]
Idk what you're doing, whatever the problem it's not coming from skeleton extensions themselves, if you want proof just check any added node from Default.json.

**Comment by GiraPomba** [comment]
Alright, I'll take a look tomorrow at the default configs then.
