### ISSUE TITLE
Attach Light: Light attached to NPC is not disabled when they enter a new cell

### ISSUE THREAD

**Issue by GiraPomba** [SlavicPotato/ied-dev#54]
When using a custom display with "Lights attached" for an NPC and the NPC enters a door, switching cells, the light is not disabled (it stays at the door entrance).

Mod in question: [https://www.nexusmods.com/skyrimspecialedition/mods/85575](https://www.nexusmods.com/skyrimspecialedition/mods/85575)
Video for reference: [https://imgur.com/zFZufXt](https://imgur.com/zFZufXt)

**Comment by SlavicPotato** [comment]
Looks like a vanilla bug, behaves the same with vanilla and IED-attached lights (see video). In my test case, the light disappears after a few seconds.

https://www.youtube.com/watch?v=A40IiBzOCRU

**Comment by GiraPomba** [comment]
Hmm. It probably is yeah. Could also be some other mod in my load order, since the light stays a bit longer. Light Limit Fix maybe.

I "fix" it by also changing cells.

**Comment by SlavicPotato** [comment]
Actor lights have an netimmerse object (attached to the skeleton) and a separate, light-emitting object (BSLight) that follows the former around. The light-emitting object is problematic since it won't get cleaned up until the actor 3D unloads which typically doesn't happen when it transitions from exterior to interior cells - for example, that npc that walked into the bannered mare still has its 3D loaded. 

So yeah, this issue is present for any actor-attached light. IED would need to explicitly clean up (and then re-add) the light in such cases and the engine would have to be patched to do the same for vanilla lights.

**Comment by GiraPomba** [comment]
I understand.
Does this happens with torches too?

Well, not sure if this falls in the scope of the mod or if it's something easy to do. Personally, it doesn't bother me much.

**Comment by SlavicPotato** [comment]
> Does this happens with torches too?

Yes. As long as the torch 3D is loaded, even if the actor is in another cell, the light remains at the position where the actor exited the load zone. It really easy to test this with console commands, i.e. <refid>.cast or <refid>.equipitem (see the brief console popup in the video i posted).

> Well, not sure if this falls in the scope of the mod

It's a bit of a grey area. I tend to shove in fixes relevant to the mod (VanillaLightCellAttachFix for example), but It would be better to just release a separate mod.

> if it's something easy to do

I doubt it

**Comment by GiraPomba** [comment]
Sounds like a good mod idea if you are up for the challenge. haha
